# Generated by Django 5.1.7 on 2025-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('Brazil', 'Brasil'), ('Portugal', 'Portugal'), ('Germany', 'Alemanha'), ('France', 'Franca'), ('Italy', 'Italia'), ('Spain', 'Espanha'), ('England', 'Inglaterra'), ('Mexico', 'Mexico'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Peru', 'Peru'), ('Bolivia', 'Bolivia')], max_length=50, null=True)),
            ],
        ),
    ]
